### ISSUE TITLE
Fix the SETUP tutorial please

### ISSUE THREAD

**Issue by anumerico** [NASA-IMPACT/hls-foundation-os#24]
We've been trying to make that work for 24 hours now following your instructions in the repo.
It seems hopeless.
Would be nice to have good resources for the Nasa Space APPS.
Command:
mim train mmsegmentation /content/mmsegmentation/hls-foundation-os/configs/multi_temporal_crop_classification.py
Error:
from mmcv.cnn.utils import revert_sync_batchnorm
ImportError: cannot import name 'revert_sync_batchnorm' from 'mmcv.cnn.utils'

**Comment by CarlosGomes98** [comment]
Hi @anumerico . Can you please confirm the version of mmcv you have installed? Version 1.6.2 should have revert_sync_batchnorm in  mmcv.cnn.utils

**Comment by anumerico** [comment]
Ok, some progress with that..
Now getting a new error:
ail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '

return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by anumerico** [comment]
mmcv-full fixes it and now getting:
UserWarning: `--gpus` is deprecated because we only support single GPU mode in non-distributed training. Use `gpus=1` now.
  warnings.warn('`--gpus` is deprecated because we only support '

**Comment by CarlosGomes98** [comment]
Could you confirm that you've installed `mmcv-full`, and not `mmcv`? The error message seems to suggest that you do not have `mmcv-full`.

Not the install in the readme for mmcv is `mim install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/{cuda_version}/{torch_version}/index.html`

**Comment by CarlosGomes98** [comment]
> mmcv-full fixes it and now getting: UserWarning: `--gpus` is deprecated because we only support single GPU mode in non-distributed training. Use `gpus=1` now. warnings.warn('`--gpus` is deprecated because we only support '

This is just a warning, and should be ok :) you may drop the  `--launcher pytorch` part of the command if you are training on single gpu, and that warning should disappear as a result

**Comment by anumerico** [comment]
No, I actually get to that warning already dropping the ```--launcher pytorch``` if not i get another error:
TypeError: FormatCode() got an unexpected keyword argument 'verify'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 39863) of binary: /usr/local/bin/python3.10
And in fact when i drop the launcher i get more than the warning:
 text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'

**Comment by CarlosGomes98** [comment]
This is probably from that python 3.9 prerequisite, yes. you can try `pip install yapf==0.40.1`, which may fix this (might require an uninstall of yapf first)

**Comment by anumerico** [comment]
I was cutting corners to make it work in colab, that might be it.. 
Do you know how to run that command in colab?:
!conda activate <environment-name>

**Comment by anumerico** [comment]
Found a way, hopefully this time can make it work..
Thanks for your support.

**Comment by anumerico** [comment]
Managed to sort out the former, now Im here:
COMMAND:
mim install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu115/torch1.11.0/index.htm
ERROR:
Building wheels for collected packages: mmcv-full
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for mmcv-full (setup.py) ... error
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects

**Comment by anumerico** [comment]
Still here have tried again to really stick to the instructions, still not working, its ridiculous just the setup has all those issues, very annoying.

**Comment by agraham9966** [comment]
I had finally managed to install things... or so I _thought_. Now I get the same issue mentioned above when running model_inference.py : 
"UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. etc. etc... ImportError: DLL load failed while importing _ext: The specified procedure could not be found."

I definitely, 100% have mmcv-full v1.6.2. I installed it via: mim install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu115/torch1.11.0/index.html

Could the version of torch or another package cause this error to pop up? 

Also, I kindly request the setup tutorial get some new or updated instructions. The general setup using 'pip install -e .' in the root throws errors about the length of windows paths being too long on two machines I tested (both Windows 10). I had to make a workaround for this by checking-out the specific commit of mmsegmentation specified in setup.py and installing from source. There were other things I needed to do as well which deviated from the original steps. It would be interesting to know what others did to get their setups running.

**Comment by agraham9966** [comment]
I was so near defeat, but alas I have prevailed on top! I am now able to run model_inference.py. Haven't tried training etc. so not sure if I will run into other issues. But this is how I got it working on my local machine (Windows 10). Hope this helps others who are also having issues with setup: 

```
conda create -n hlsdl python=3.9

pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113

git clone https://github.com/NASA-IMPACT/hls-foundation-os.git D:\hls-foundation-os

# cloning mmsegmentation to local dir (short directory path) 
git clone https://github.com/open-mmlab/mmsegmentation.git D:\mmsegmentation 

cd D:\mmsegmentation 

git checkout 186572a3ce64ac9b6b37e66d58c76515000c3280 # commit used for hls-foundation 

cd D:\hls-foundation-os
```
At this point I had to modify setup.py. Running 'pip install -e .' was throwing errors since it was trying to install mmsegmentation in a temp directory, which exceeded the allowable character limit in windows. I suspect others will have this issue as well since I tried on two machines and same issue. The workaround was to modify setup.py so it installs from the cloned mmsegmentation:

```
from setuptools import setup

setup(
    name='geospatial_fm',
    version='0.1.0',    
    description='MMSegmentation classes for geospatial-fm finetuning',
    author='Paolo Fraccaro, Carlos Gomes, Johannes Jakubik',
    packages=['geospatial_fm'],
    license="Apache 2",
    long_description=open("README.md").read(),
install_requires=
[
    "mmsegmentation @ file:///D:/mmsegmentation",
    "rasterio",
    "tifffile",
    "einops",
    "timm==0.4.12",
    "tensorboard",
    "imagecodecs"
    ]
)
```
 
Then continue with setup: 

```
pip install -e .     

pip install -U openmim

mim install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu115/torch1.11.0/index.html

conda install -c conda-forge opencv

pip install datasets 
```
Doing this got it to work on my machine. What a hack job but works. Hope all the pain and suffering I went through at least helps someone.

**Comment by CarlosGomes98** [comment]
Hi,Thank you so much for your work on this! It's always hard to support windows because of sneaky issues like these...I would really encourage you to submit a PR with these steps added to the README as a special case for Windows users. Like this, this would be logged as a contribution from you to this open source community :)On Oct 26, 2023 01:33, agraham9966 ***@***.***> wrote:
I was so near defeat, but alas I have prevailed on top! I am now able to run model_inference.py. Haven't tried training etc. so not sure if I will run into other issues. But this is how I got it working on my local machine (Windows 10). Hope this helps others who are also having issues with setup:
conda create -n hlsdl python=3.9

pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113

git clone https://github.com/NASA-IMPACT/hls-foundation-os.git D:\hls-foundation-os

# cloning mmsegmentation to local dir (short directory path) 
git clone https://github.com/open-mmlab/mmsegmentation.git D:\mmsegmentation 

cd D:\mmsegmentation 

git checkout 186572a3ce64ac9b6b37e66d58c76515000c3280 # commit used for hls-foundation 

cd D:\hls-foundation-os

At this point I had to modify setup.py. Running 'pip install -e .' was throwing errors since it was trying to install mmsegmentation in a temp directory, which exceeded the allowable character limit in windows. I suspect others will have this issue as well since I tried on two machines and same issue. The workaround was to modify setup.py so it installs from the cloned mmsegmentation:
from setuptools import setup

setup(
    name='geospatial_fm',
    version='0.1.0',    
    description='MMSegmentation classes for geospatial-fm finetuning',
    author='Paolo Fraccaro, Carlos Gomes, Johannes Jakubik',
    packages=['geospatial_fm'],
    license="Apache 2",
    long_description=open("README.md").read(),
install_requires=
[
    "mmsegmentation @ file:///D:/mmsegmentation",
    "rasterio",
    "tifffile",
    "einops",
    "timm==0.4.12",
    "tensorboard",
    "imagecodecs"
    ]
)

Then continue with setup:
pip install -e .     

pip install -U openmim

mim install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu115/torch1.11.0/index.html

conda install -c conda-forge opencv

pip install datasets 

Doing this got it to work on my machine. What a hack job but works. Hope all the pain and suffering I went through at least helps someone.

**Comment by agraham9966** [comment]
just a note to this - I did submit a PR. You may or may not need to downgrade yapf (described more in earlier post above): 
```
pip uninstall yapf 
pip install yapf==0.40.1  
```

I had actually done this earlier on and wasnt able to verify if I needed to or not. Its excluded from my pull request for now but if someone else tries my set up and finds you need to do this please let me know. 

Otherwise, yes, I was able to get everything working - including training - on windows 10.

**Comment by CarlosGomes98** [comment]
Pushed changes to address this. Linked to #42.

**Comment by LucFrachon** [comment]
> I was so near defeat, but alas I have prevailed on top! I am now able to run model_inference.py. Haven't tried training etc. so not sure if I will run into other issues. But this is how I got it working on my local machine (Windows 10). Hope this helps others who are also having issues with setup:
> 
> ```
> conda create -n hlsdl python=3.9
> 
> pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
> 
> git clone https://github.com/NASA-IMPACT/hls-foundation-os.git D:\hls-foundation-os
> 
> # cloning mmsegmentation to local dir (short directory path) 
> git clone https://github.com/open-mmlab/mmsegmentation.git D:\mmsegmentation 
> 
> cd D:\mmsegmentation 
> 
> git checkout 186572a3ce64ac9b6b37e66d58c76515000c3280 # commit used for hls-foundation 
> 
> cd D:\hls-foundation-os
> ```
> 
> At this point I had to modify setup.py. Running 'pip install -e .' was throwing errors since it was trying to install mmsegmentation in a temp directory, which exceeded the allowable character limit in windows. I suspect others will have this issue as well since I tried on two machines and same issue. The workaround was to modify setup.py so it installs from the cloned mmsegmentation:
> 
> ```
> from setuptools import setup
> 
> setup(
>     name='geospatial_fm',
>     version='0.1.0',    
>     description='MMSegmentation classes for geospatial-fm finetuning',
>     author='Paolo Fraccaro, Carlos Gomes, Johannes Jakubik',
>     packages=['geospatial_fm'],
>     license="Apache 2",
>     long_description=open("README.md").read(),
> install_requires=
> [
>     "mmsegmentation @ file:///D:/mmsegmentation",
>     "rasterio",
>     "tifffile",
>     "einops",
>     "timm==0.4.12",
>     "tensorboard",
>     "imagecodecs"
>     ]
> )
> ```
> 
> Then continue with setup:
> 
> ```
> pip install -e .     
> 
> pip install -U openmim
> 
> mim install mmcv-full==1.6.2 -f https://download.openmmlab.com/mmcv/dist/cu115/torch1.11.0/index.html
> 
> conda install -c conda-forge opencv
> 
> pip install datasets 
> ```
> 
> Doing this got it to work on my machine. What a hack job but works. Hope all the pain and suffering I went through at least helps someone.

@agraham9966 THANK YOU!!! I was so close to giving up, but your recommendations are the only ones that made it work for me -- and I'm on Ubuntu, not Windows. I would just add rasterio back to the package list in setup.py, and yes, uninstalling and downgrading yapf was required for me.
